apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cosy-gameapi
  namespace: cosy
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  rules:
    - host: cosy-game-api.jannekeipert.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cosy-gameapi
                port:
                  number: 80
  tls:
    - hosts:
        - cosy-game-api.jannekeipert.de
      secretName: multi-domain-cert   
