apiVersion: v1
kind: Service
metadata:
  name: cosy-gameapi
  namespace: cosy
spec:
  selector:
    app: cosy-gameapi
  ports:
    - port: 80        # inside the cluster
      targetPort: 8080
      protocol: TCP
  type: ClusterIP

